port 26379
bind 0.0.0.0
protected-mode no
sentinel resolve-hostnames yes
sentinel announce-hostnames yes
sentinel announce-ip redis-sentinel-3
sentinel announce-port 26379
sentinel monitor coffee-order-redis redis-master 6379 2
sentinel down-after-milliseconds coffee-order-redis 5000
sentinel failover-timeout coffee-order-redis 30000
sentinel parallel-syncs coffee-order-redis 1
