spring.application.name=coffee-order-system

app.datasource.primary.url=${DB_PRIMARY_URL:${DB_URL:jdbc:mysql://localhost:${MYSQL_PRIMARY_PORT:3307}/${MYSQL_DATABASE:coffee_order}?connectionTimeZone=UTC&forceConnectionTimeZoneToSession=true&characterEncoding=UTF-8}}
app.datasource.primary.username=${DB_PRIMARY_USERNAME:${DB_USERNAME:coffee_user}}
app.datasource.primary.password=${DB_PRIMARY_PASSWORD:${DB_PASSWORD:coffee_password}}
app.datasource.primary.driver-class-name=com.mysql.cj.jdbc.Driver

app.datasource.replica.url=${DB_REPLICA_URL:jdbc:mysql://localhost:${MYSQL_REPLICA_PORT:3308}/${MYSQL_DATABASE:coffee_order}?connectionTimeZone=UTC&forceConnectionTimeZoneToSession=true&characterEncoding=UTF-8}
app.datasource.replica.username=${DB_REPLICA_USERNAME:${DB_USERNAME:coffee_user}}
app.datasource.replica.password=${DB_REPLICA_PASSWORD:${DB_PASSWORD:coffee_password}}
app.datasource.replica.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
popular-menu-cache.ttl-seconds=${POPULAR_MENU_CACHE_TTL_SECONDS:86400}
popular-menu-cache.enabled=${POPULAR_MENU_CACHE_ENABLED:true}
