package com.example.coffeeordersystem.config;

import com.example.coffeeordersystem.domain.Menu;
import com.example.coffeeordersystem.domain.MenuStatus;
import com.example.coffeeordersystem.domain.PointWallet;
import com.example.coffeeordersystem.domain.User;
import com.example.coffeeordersystem.dto.MenuResponse;
import com.example.coffeeordersystem.repository.MenuRepository;
import com.example.coffeeordersystem.repository.PointWalletRepository;
import com.example.coffeeordersystem.repository.UserRepository;
import com.example.coffeeordersystem.service.MenuService;
import com.example.coffeeordersystem.service.OrderService;
import com.example.coffeeordersystem.service.PointChargeService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.ActiveProfiles;

import javax.sql.DataSource;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

/** 실제 JPA Service·Repository 호출이 Primary와 Replica를 구분하는지 검증한다. */
@SpringBootTest(properties = {
		"app.datasource.primary.url=jdbc:h2:mem:replication_primary;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE",
		"app.datasource.primary.username=sa",
		"app.datasource.primary.password=",
		"app.datasource.primary.driver-class-name=org.h2.Driver",
		"app.datasource.replica.url=jdbc:h2:mem:replication_replica;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE",
		"app.datasource.replica.username=sa",
		"app.datasource.replica.password=",
		"app.datasource.replica.driver-class-name=org.h2.Driver",
		"popular-menu-cache.enabled=false"
})
@ActiveProfiles("prod")
class ReplicationJpaRoutingIntegrationTest {

	private final MenuService menuService;
	private final OrderService orderService;
	private final PointChargeService pointChargeService;
	private final UserRepository userRepository;
	private final MenuRepository menuRepository;
	private final PointWalletRepository pointWalletRepository;
	private final JdbcTemplate primaryJdbcTemplate;
	private final JdbcTemplate replicaJdbcTemplate;

	@Autowired
	ReplicationJpaRoutingIntegrationTest(
			MenuService menuService,
			OrderService orderService,
			PointChargeService pointChargeService,
			UserRepository userRepository,
			MenuRepository menuRepository,
			PointWalletRepository pointWalletRepository,
			@Qualifier("primaryDataSource") DataSource primaryDataSource,
			@Qualifier("replicaDataSource") DataSource replicaDataSource
	) {
		this.menuService = menuService;
		this.orderService = orderService;
		this.pointChargeService = pointChargeService;
		this.userRepository = userRepository;
		this.menuRepository = menuRepository;
		this.pointWalletRepository = pointWalletRepository;
		this.primaryJdbcTemplate = new JdbcTemplate(primaryDataSource);
		this.replicaJdbcTemplate = new JdbcTemplate(replicaDataSource);
	}

	@BeforeEach
	void setUpReplicaMenuTable() {
		replicaJdbcTemplate.execute("""
				CREATE TABLE IF NOT EXISTS menu (
					id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
					name VARCHAR(100) NOT NULL,
					price BIGINT NOT NULL,
					status VARCHAR(20) NOT NULL,
					created_at TIMESTAMP NOT NULL,
					updated_at TIMESTAMP NOT NULL
				)
				""");
		replicaJdbcTemplate.update("DELETE FROM menu");
		primaryJdbcTemplate.update("DELETE FROM outbox_events");
		primaryJdbcTemplate.update("DELETE FROM point_history");
		primaryJdbcTemplate.update("DELETE FROM orders");
		menuRepository.deleteAll();
		pointWalletRepository.deleteAll();
		userRepository.deleteAll();
	}

	@Test
	void 메뉴_조회는_실제_JPA_Repository를_거쳐_Replica_데이터를_반환한다() {
		menuRepository.save(Menu.create("primary-only", 3000L, MenuStatus.ACTIVE));
		replicaJdbcTemplate.update("""
				INSERT INTO menu (name, price, status, created_at, updated_at)
				VALUES ('replica-only', 4000, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
				""");

		List<MenuResponse> response = menuService.findActiveMenus();

		assertThat(response).extracting(MenuResponse::name).containsExactly("replica-only");
	}

	@Test
	void 주문과_비관적_지갑_조회는_Primary에서_처리된다() {
		User user = userRepository.save(User.create("order-primary-user"));
		pointWalletRepository.save(PointWallet.create(user, 10000L));
		Menu menu = menuRepository.save(Menu.create("order-primary-menu", 3000L, MenuStatus.ACTIVE));

		orderService.order(user.getId(), menu.getId());

		assertThat(primaryJdbcTemplate.queryForObject(
				"SELECT balance FROM point_wallet WHERE user_id = ?", Long.class, user.getId())).isEqualTo(7000L);
		assertThat(primaryJdbcTemplate.queryForObject("SELECT COUNT(*) FROM orders", Long.class)).isEqualTo(1L);
	}

	@Test
	void 포인트_충전은_Primary에서_처리된다() {
		User user = userRepository.save(User.create("charge-primary-user"));
		pointWalletRepository.save(PointWallet.create(user, 0L));

		pointChargeService.charge(user.getId(), 5000L);

		assertThat(primaryJdbcTemplate.queryForObject(
				"SELECT balance FROM point_wallet WHERE user_id = ?", Long.class, user.getId())).isEqualTo(5000L);
	}
}
